[theme]
theme = "plain"

[icons]
icons = "none"

[[block]]
block = "custom"
command = "ip addr show tailscale0 2>/dev/null | grep -oP '100\\.\\d+\\.\\d+\\.\\d+' | head -1"
format = " TS: $text.str() "
interval = 10
hide_when_empty = true

[[block]]
block = "net"
device = "wlp3s0"
format = " Net: $ssid $ip $speed_down.eng(w:3,prefix:M)↓ $speed_up.eng(w:3,prefix:M)↑ "
interval = 2

[[block]]
block = "cpu"
format = " CPU: $utilization.eng(w:4) "
interval = 5

[[block]]
block = "memory"
format = " RAM: $mem_used.eng(w:3)/$mem_total.eng(w:3) "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = " Disk: $available.eng(w:5) "
interval = 20

[[block]]
block = "sound"
format = " Vol: $volume.eng(w:4) "

[[block]]
block = "battery"
device = "BAT0"
driver = "sysfs"
format = " Bat0: $percentage "
full_format = " Bat0: $percentage "
not_charging_format = " Bat0: $percentage "
interval = 30

[[block]]
block = "battery"
device = "BAT1"
driver = "sysfs"
format = " Bat1: $percentage "
full_format = " Bat1: $percentage "
not_charging_format = " Bat1: $percentage "
interval = 30

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d %b  %H:%M') "
interval = 60
